# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sshkg}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Javier Juarez"]
  s.date = %q{2010-10-04}
  s.default_executable = %q{sshkg}
  s.description = %q{A wrapper over ssh-keygem for rubyists}
  s.email = %q{javier.juarez@gmail.com}
  s.executables = ["sshkg"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "bin/sshkg",
     "lib/sshkg.rb",
     "lib/sshkg/config.rb",
     "lib/sshkg/generator.rb",
     "lib/sshkg/version.rb",
     "lib/util/opt_parser.rb"
  ]
  s.homepage = %q{http://github.com/jjuarez/sshkg}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A very simple gem that helps to automate the generation of SSH Keys}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

